// data.js — CEINYS project data (standalone — photoKey lifted)
window.CEINYS_PROJECTS = [
  { id: 'la-palma',     brand: 'la-palma',     nombre: 'La Palma Paracas',  tipo: 'Lotes residenciales',
    chip: 'En venta',           chipTone: 'venta',
    descripcion: '120 a 318 m² frente al corredor costero de Paracas.',
    zona: 'Paracas, Pisco', photoKey: 'photoLaPalma' },
  { id: 'sol-carhuaz',  brand: 'sol-carhuaz',  nombre: 'Sol de Carhuaz',    tipo: 'Megaproyecto urbano',
    chip: 'En venta · Etapa 4', chipTone: 'etapa',
    descripcion: '5 etapas con servicios completos. Lotes desde 104 m².',
    zona: 'Ica', photoKey: 'photoSolCarhuaz' },
  { id: 'monte-alegre', brand: 'monte-alegre', nombre: 'Monte Alegre',      tipo: 'Lotes urbanos accesibles',
    chip: 'Próximamente',       chipTone: 'proximo',
    descripcion: 'Lotes de 90, 105 y 120 m² en Carretera Carhuaz Km 8.',
    zona: 'Ica', photoKey: 'photoMonteAlegre' },
  { id: 'valle-sacta',  brand: 'valle-sacta',  nombre: 'Valle Sacta',       tipo: 'Casas de campo',
    chip: 'En venta',           chipTone: 'venta',
    descripcion: 'Lotes amplios de 500 a 1,600 m² en zona Pachacutec.',
    zona: 'Ica', photoKey: 'photoValleSacta' },
  { id: 'altos-sacta',  brand: 'altos-sacta',  nombre: 'Altos de Sacta',    tipo: 'Casas de campo',
    chip: 'En venta',           chipTone: 'venta',
    descripcion: 'Extensión natural de Valle Sacta. Lotes amplios y áreas verdes generosas.',
    zona: 'Ica', photoKey: 'photoAltosSacta', url: 'proyectoaltos.html' },
  { id: 'los-sauces',   brand: 'los-sauces',   nombre: 'Los Sauces',        tipo: 'Condominio entry-level',
    chip: 'Etapa 5 en venta',   chipTone: 'etapa',
    descripcion: '4 etapas entregadas al 100%. Lotes de 200 m².',
    zona: 'Ica', photoKey: 'photoLosSauces' },
];
